// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeDirectory(arg1:string):Promise<string>;

export function Create(arg1:string,arg2:string):Promise<string>;

export function GetInitialData():Promise<string>;
